### ISSUE TITLE
Cannot create topics without setting retention-time

### ISSUE THREAD

**Issue by justindowning** [heroku/heroku-kafka-jsplugin#159]
Using v6 of heroku cli throws an error with using `kafka:topics:create`:

```
ᐅ heroku kafka:topics:create messages --app my-test-app
 ▸    Cannot read property 'match' of undefined
TypeError: Cannot read property 'match' of undefined
    at parseDuration (/Users/jdowning/.local/share/heroku/plugins/node_modules/heroku-kafka/lib/shared.js:50:29)
    at createTopic (/Users/jdowning/.local/share/heroku/plugins/node_modules/heroku-kafka/commands/topics_create.js:18:27)
    at createTopic.next (<anonymous>)
    at onFulfilled (/Users/jdowning/.local/share/heroku/plugins/node_modules/co/index.js:65:19)
    at /Users/jdowning/.local/share/heroku/plugins/node_modules/co/index.js:54:5
    at co (/Users/jdowning/.local/share/heroku/plugins/node_modules/co/index.js:50:10)
    at createPromise (/Users/jdowning/.local/share/heroku/plugins/node_modules/co/index.js:30:15)
    at run (/Users/jdowning/.local/share/heroku/plugins/node_modules/heroku-cli-util/lib/command.js:123:15)
    at Object.run (/Users/jdowning/.local/share/heroku/plugins/node_modules/heroku-cli-util/lib/command.js:140:12)
    at V5.run (/Users/jdowning/.local/share/heroku/client/node_modules/cli-engine/lib/plugins/legacy.js:55:16)
    at Function.run (/Users/jdowning/.local/share/heroku/client/node_modules/cli-engine-command/lib/command.js:56:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
Exiting with code: 0
```

The [relevant code](https://github.com/heroku/heroku-kafka-jsplugin/blob/02d5ac46a3b5057be1e9e50a93f7a5272796dfd7/commands/topics_create.js#L17-L22) shouldn't run if we don't set a retention-time flag.

Running with `--retention-time` works:

```
ᐅ heroku kafka:topics:create messages --retention-time 1d --app my-test-app
Creating topic messages with compaction disabled and retention time 1 day on kafka-rectangular-79428... done
Use `heroku kafka:topics:info messages` to monitor your topic.
```

```
ᐅ heroku version
heroku-cli/6.6.19-9135689 (darwin-x64) node-v7.9.0
```

**Comment by uhoh-itsmaciek** [comment]
@justindowning how can you tell that is the relevant code? The error you pasted seems to suggest something different.

**Comment by justindowning** [comment]
@uhoh-itsmaciek Gah! I posted the wrong error message. I edited with the correct trace showing the LOC affected.

**Comment by uhoh-itsmaciek** [comment]
Ok, good catch. I think I know why. Fixing.
