### ISSUE TITLE
Install fails on Amazon Linux

### ISSUE THREAD

**Issue by slepkin** [heroku/heroku-kafka-jsplugin#180]
On a fresh EC2 instance, using the default image, `heroku plugins:install heroku-kafka` fails.

Here's how we install the CLI:

```
export PATH=$PATH:/usr/local/bin
wget -qO heroku.tar.gz https://cli-assets.heroku.com/branches/stable/heroku-linux-amd64.tar.gz
mkdir -p /usr/local/lib
tar -xzf heroku.tar.gz -C /usr/local/lib
/usr/local/lib/heroku/install
```

This works fine for core CLI plugins (ex: pg). However, installation fails for this plugin:

```
$ sudo /usr/local/bin/heroku plugins:install heroku-kafka
Installing plugin heroku-kafka... ⣾
Installing plugin heroku-kafka... !
 ▸    yarn --non-interactive --mutex=file:/root/.cache/heroku/yarn --cache-folder=/root/.cache/heroku/yarn exited with code 1
 ▸    error /root/.local/share/heroku/plugins/node_modules/snappy: Command failed.
 ▸    Exit code: 1
 ▸    Command: sh
 ▸    Arguments: -c ./node_modules/.bin/node-gyp rebuild
 ▸    Directory: /root/.local/share/heroku/plugins/node_modules/snappy
 ▸    Output:
 ▸    gyp info it worked if it ends with ok
 ▸    gyp info using node-gyp@3.4.0
 ▸    gyp info using node@9.2.0 | linux | x64
 ▸    gyp info spawn /usr/bin/python
 ▸    gyp info spawn args [ '/root/.local/share/heroku/plugins/node_modules/node-gyp/gyp/gyp_main.py',
 ▸    gyp info spawn args   'binding.gyp',
 ▸    gyp info spawn args   '-f',
 ▸    gyp info spawn args   'make',
 ▸    gyp info spawn args   '-I',
 ▸    gyp info spawn args   '/root/.local/share/heroku/plugins/node_modules/snappy/build/config.gypi',
 ▸    gyp info spawn args   '-I',
 ▸    gyp info spawn args   '/root/.local/share/heroku/plugins/node_modules/node-gyp/addon.gypi',
 ▸    gyp info spawn args   '-I',
 ▸    gyp info spawn args   '/root/.node-gyp/9.2.0/include/node/common.gypi',
 ▸    gyp info spawn args   '-Dlibrary=shared_library',
 ▸    gyp info spawn args   '-Dvisibility=default',
 ▸    gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/9.2.0',
 ▸    gyp info spawn args   '-Dnode_gyp_dir=/root/.local/share/heroku/plugins/node_modules/node-gyp',
 ▸    gyp info spawn args   '-Dnode_lib_file=node.lib',
 ▸    gyp info spawn args   '-Dmodule_root_dir=/root/.local/share/heroku/plugins/node_modules/snappy',
 ▸    gyp info spawn args   '--depth=.',
 ▸    gyp info spawn args   '--no-parallel',
 ▸    gyp info spawn args   '--generator-output',
 ▸    gyp info spawn args   'build',
 ▸    gyp info spawn args   '-Goutput_dir=.' ]
 ▸    gyp info spawn make
 ▸    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
 ▸    make: Entering directory `/root/.local/share/heroku/plugins/node_modules/snappy/build'
 ▸    CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o
 ▸    make: g++: Command not found
 ▸    make: *** [Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o] Error 127
 ▸    gyp ERR! build error
 ▸    gyp ERR! stack Error: `make` failed with exit code: 2
 ▸    gyp ERR! stack     at ChildProcess.onExit (/root/.local/share/heroku/plugins/node_modules/node-gyp/lib/build.js:276:23)
 ▸    gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
 ▸    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
 ▸    gyp ERR! System Linux 4.9.27-14.31.amzn1.x86_64
 ▸    gyp ERR! command "/root/.local/share/heroku/client/bin/node" "/root/.local/share/heroku/plugins/node_modules/snappy/node_modules/.bin/node-gyp" "rebuild"
 ▸    gyp ERR! cwd /root/.local/share/heroku/plugins/node_modules/snappy
 ▸    gyp ERR! node -v v9.2.0
 ▸    gyp ERR! node-gyp -v v3.4.0
 ▸    gyp ERR! not ok
 ▸    make: Leaving directory `/root/.local/share/heroku/plugins/node_modules/snappy/build'
 ▸    
```

Is there some dependency we're missing? I saw the alert in [the docs](https://devcenter.heroku.com/articles/kafka-on-heroku#preparing-your-development-environment) about installing the plugin on Windows, but that probably doesn't apply here. `npm` is installed, in case that matters.

**Comment by tcrayford** [comment]
@slepkin yep, this is because `g++` isn't installed.

**Comment by slepkin** [comment]
Yep, `yum install gcc-c++` did the trick. Thanks!

**Comment by jdxcode** [comment]
I don't think there is anything I can do in order to improve the experience here sadly. I could potentially show some custom messaging when installing a plugin, but that's hard since I don't have access to the plugin files even until after yarn installs the package, so I would have to fetch that separately.

**Comment by idan** [comment]
@jdxcode more of an FYI so we know that this is an annoying failure mode that we uh can't really deal with.

**Comment by jdxcode** [comment]
yeah thanks for letting me know, mostly was just thinking out loud. I did recently improve the linked experience of working with native deps (they should always automatically rebuild now), but this is likely still an issue
